name: nvim-metals ci

on:
  push:
    branches:
      - main
      - next
  pull_request:

jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Setup luacheck
      run: |
        sudo apt update &&
        sudo apt install -y lua5.1 luarocks &&
        sudo luarocks install luacheck

    - name: Run luacheck
      run: |
        make lint

  format-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup StyLua
      run: |
        cargo install --version 0.9.3 stylua

    - name: Run StyLua
      run: |
        make format-check
